main: fr.lataverne.itemreward.ItemReward

name: ItemReward

description: Manages custom items

authors:
  - syuko

version: 1.0.0

api-version: 1.17

commands:
  itemreward:
    description: Command of the ItemReward plugin
    usage: "Usage: /itemreward [itemName]"
    permission: ir.command
    default: op
    aliases:
      - itemreward
      - ir

permissions:
  ir.*:
    description: Adds all permissions
    default: op
    children:
      ir.get: true
  ir.get:
    description: Allows you to give yourself an item
    default: op