main: fr.lataverne.itemreward.ItemReward

name: ItemReward

description: Manages custom items

authors:
  - syuko

version: 1.0.0

api-version: 1.17

commands:
  itemreward:
    description: Command of the ItemReward plugin
    usage: "Usage: /itemreward help"
    aliases:
      - itemreward
      - ir

permissions:
  ir.*:
    description: Adds all permissions
    default: op
    children:
      ir.give: true
      ir.list: true
      ir.help: true
  ir.give:
    description: Allows player to give custom items
    default: op
  ir.list:
    description: Allows player to list all custom items
    default: op
  ir.help:
    description: Allows player to use the help command
    default: op